### ISSUE TITLE
运行命令加载proxy.list 文件报错 （命令：getproxy --in-proxy proxylist/proxy.list --out-proxy test.txt)

### ISSUE THREAD

**Issue by aiwennba** [fate0/getproxy#8]
ERROR:getproxy.plugin.freeproxylist:[-] Request page 0 error: HTTPSConnectionPool(host='free-proxy-list.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6307bba250>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR:getproxy.plugin.freeproxylist:[-] Request page 0 error: HTTPSConnectionPool(host='free-proxy-list.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6307f4b610>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python2.7/dist-packages/getproxy/plugin/freeproxylist.py", line 46, in start
    page_result = self.extract_proxy(0)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python2.7/dist-packages/getproxy/plugin/freeproxylist.py", line 39, in extract_proxy
    raise e
ConnectionError: HTTPSConnectionPool(host='free-proxy-list.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6307f4b610>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-01-07T06:16:12Z <Greenlet "Greenlet-0" at 0x7f6307606788: <bound method Proxy.start of <getproxy.plugin.freeproxylist.Proxy object at 0x7f63074c69d0>>> failed with ConnectionError

**Comment by fate0** [comment]
主要是网络的问题
